### ISSUE TITLE
resources required for brainhack event

### ISSUE THREAD

**Issue by stebo85** [brainhackorg/brainhack_cloud#14]
The Oracle team would like to know which resources we need for the brainhack in which geo-regions (GPUs need to be requested in advance so they are available in the right data centres)

- [x] How can we get an estimate on this?
- [ ] We need to request the resources in the region where it's available: https://www.oracle.com/cloud/data-regions/#northamerica
- [x] We need to subscribe to the regions where users need resources

**Comment by stebo85** [comment]
I subscribed to almost all regions now

**Comment by likeajumprope** [comment]
We are still finalising the number of participants.
Would it be good if we selected the region close to the actual location of people? We will have many people in schotland (face to face attendees) but I could get an overview at least form where people have registered

**Comment by stebo85** [comment]
yes, a rough list would be useful - then we can prepare and request resources in these regions

**Comment by stebo85** [comment]
I am just waiting on the Oracle team to let me know where they have many GPUs and then I will request them for the event.

**Comment by stebo85** [comment]
We have GPUs in Tokyo and I will apply for GPUs in London and Frankfurt as well.
