### ISSUE TITLE
Real-time shared data visualisation on the web with NiiVue

### ISSUE THREAD

**Issue by hanayik** [brainhackorg/brainhack_cloud#16]
### Title

Real-time shared data visualisation on the web with NiiVue

### Is this a new project?

yes

### People involved

- Taylor Hanayik @hanayik
- Chris Rorden @neurolabusc
- Chris Drake @cdrake

I'm not listing emails of collaborators without their consent, but I have linked to their public GitHub profiles. 

### Project Description

The primary aim of NiiVue is to translate the features of the widely used native desktop applications ([MRIcroGL](https://github.com/rordenlab/MRIcroGL), [Surfice](https://github.com/neurolabusc/surf-ice)) to their web-based equivalents. This will enable other researchers and developers to build cloud-based medical imaging tools with a powerful viewer that can operate on any device (desktop, tablet, mobile).

We are requesting resources to facilitate one of our goals: Real-time, shared visualisation in the browser. Specifically, a cloud VM will be used to host a WebSocket server that allows multiple NiiVue clients to share data with each other securely, and enable research collaboration and synchronisation in real-time across the globe. 

### Link to project repository/sources

https://github.com/niivue/niivue

### What resources do you require?

Virtual Machines

**Comment by stebo85** [comment]
Dear 

Taylor Hanayik @hanayik
Chris Rorden @neurolabusc
Chris Drake @cdrake

The project is provisioned. Let us know here if you encounter any issues :)

Thank you for being one of the first =)

Cheers
Steffefn

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
