### ISSUE TITLE
Cloud and HPC-based Neuroimaging Research Education for Novice Users

### ISSUE THREAD

**Issue by jrabsher** [brainhackorg/brainhack_cloud#31]
### Title

**A Uniform Environment for Cloud and HPC-based Neuroimaging Research Education for Novice Users**

### Is this a new project?

yes

### People involved

John Absher, jrabsher, absher@mailbox.sc.edu, jabsher@clemson.edu
Grigori Yourganov, grigori-yourganov, gyourga@clemson.edu
Taylor Hanayik, hanayik, taylor.hanayik@ndcn.ox.ac.uk
Chris Rorden, neurolabusc, RORDEN@mailbox.sc.edu

### Project Description

**Introduction**
Neuroimaging research education for novice users typically requires a graphical user interface, because novice users lack familiarity with the command line. Meanwhile, the field of neuroimaging research increasingly utilizes cloud-based computing resources, data storage structures, and high performance computing environments. Along with these formidable technical challenges, there is increasing awareness of the need for reproducible data science, to assure that data, code, analysis and results are susceptible to peer review and scientific scrutiny. We believe that novice neuroimaging research students (from high school through professional levels of education) who utilize the same interface (e.g., NeuroDesk) in both a cloud-based learning/collaboration environment and an HPC production environment will be able to spend more time focusing on neuroscience/neuroimaging, and less time struggling with the technical complexities of these environments.
**Background**
For the past 5 years, the Structured Neuroimaging-Intensive Research Program (SNIRP) has introduced students to basic aspects of neuroimaging research. The program began with 2 undergraduate students and has grown to 21 students in the 2022 summer program. A seed grant has been obtained to study whether novice users benefit from a rudimentary graphical "front end" to neuroimaging tools such as MRIcroGL, FSL, SPM, Surfice, FSLeyes, and Matlab. By examining the user experience through the lens of "user-centered design" we hope to learn how to best enhance the learning experience for novice students. We begin this journey by observing students as they engage in tutorials designed to teach them neuroimaging research procedures, starting with FSL tutorials. Ultimately, we hope to engage the developers of open-source neuroimaging research tools (Freesurfer, SPM, AFNI, etc), related collaboration websites (e.g., github, NITRC), and data repositories (e.g., UK Biobank, ida.loni.usc.edu) in the curation of tutorials that novice users could easily access within a comprehensive cloud-based learning and collaboration environment housed on Oracle Cloud.
**Methods**

1. We propose to provide 21 SNIRP students and approximately 10 faculty advisors with access to NeuroDesk on Oracle Cloud.
2. NeuroDesk will be enhanced to include a simple graphical user interface for novice users to access tutorials.
3. This modified NeuroDesk (with GUI) will be cloned, and the clone will include monitoring capability that enables robust data collection to support user-centered design enhancements of the GUI. Only students who have signed an informed consent (for our approved seed grant project) will be subjected to data collection as they complete the tutorials. 
4. The same NeuroDesk-GUI and NeuroDesk-GUI-for-research-subjects will be installed within transparent Singularity containers on the HPC Neuroimaging Research Core (HPCNIRC) environment located on the Palmetto Cluster at Clemson University. The transparent Singularity containers will allow students to access HPC resources and data on the HPCNIRC environment.
5. Students will gain critical "reproducibility" experience as they save and export their work on various tutorials from Oracle Cloud. Globus.org is utilized for large data transfers into and out of the Palmetto Cluster.
6. After demonstrating successful reproducibility using NeuroDesk on Oracle Cloud, and successful data transport into and out of the HPCNIRC, students will be able to save the products of their ongoing neuroimaging research using the same reproducible approaches they used for the tutorials.

### Link to project repository/sources

This project relies on https://github.com/NeuroDesk
/
[neurodesk.github.io](https://github.com/NeuroDesk/neurodesk.github.io)

### What resources do you require?

Virtual Machines, Object Storage, GPU resources, HPC, other

### Anything else?

As a practicing neurologist, my expertise is primarily in neuroimaging and neuroscience, rather than HPC, coding/scripting, and these highly technical areas. In fact, a prime motivation for pursuing this project is my own experience, facing the challenges of learning these skills over the past 3+ decades.
Therefore, I humbly request the ability to add a few collaborators to this project, people who can do many of the things that are difficult or impossible for me to do, or that are too time consuming for my immediate colleagues to add to their considerable lists of priorities. 

Thank you for considering this project request.

Sincerly, 

John R. Absher, MD

**Comment by SamGuay** [comment]
Thank you for your wonderful request @jrabsher!

It is the first request we proceed so please bear with us while we make sure everything works on our side while fulfilling your request. :)

You should receive more info in the coming week. 

Thank you again,

On behalf of the Brainhack Cloud team :brain: :technologist:  :cloud:

**Comment by complexbrains** [comment]
Dear @jrabsher, your project named `neuroimaging_edu_cloud`  is created and all the collaborators are added to the project. You can now navigate around the platform and familiarize yourself with the Brainhack Oracle Cloud resources. 

In the meantime, we will be adding more policies for the allocation of the resources you requested and will update you as soon as the project is ready to go! 

Dear @stebo85 could you please do have a look at the settings we have done so far, and let me or @SamGuay know if there are further settings that would require our attention.

**Comment by stebo85** [comment]
Dear @complexbrains and @SamGuay 

great work on creating the project :) Everything is good to go and the policies are now set up.

I will set-up a small Kubernetes cluster for Neurodesk for the team in the next days.

**Comment by complexbrains** [comment]
I know you are in a shortage of time and would not want to add any other workload to you but do you think would be possible to take some notes/directions regarding the Kubernetes set up when you are doing it so we would have a chance to go through it later on please? Or any pointers towards it, so we can also practice at some point please. 

But please do not worry if you cannot have time, hopefully we will have more opportunities soon to practice more of it 🤗

**Comment by stebo85** [comment]
Dear @complexbrains - I documented how to setup Kubernetes on Oracle Cloud here: https://brainhack.org/brainhack_cloud/docs/kubernetes/

From there on it's standard Kubernetes things :)

**Comment by stebo85** [comment]
@jrabsher, @grigori-yourganov,
 @hanayik, @neurolabusc

I setup a Kubernetes instance running Mybinder with Neurodesk here:
http://141.148.10.177/v2/gh/neurodesk/jupyter-neurodesktop-image/main?urlpath=neurodesktop 

It's an automatically updating version of Neurodesk, so every new instance will pull in the latest updates and I hope that works without problems as we haven't tested this much before. You can upload files via drag and drop from the desktop and downloading of files works via the guacamole interface accessible via CTRL+ALT+SHIFT

It has 200GB of RAM, 400GB of Disk space and 24 cores which should hopefully be enough for your purposes - if not, let us know and we can increase it :)

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
