### ISSUE TITLE
Make procedure to login obvious to users and admins

### ISSUE THREAD

**Issue by SamGuay** [brainhackorg/brainhack_cloud#32]
### Add bug or feature or design

- [ ] bug report
- [X] feature request
- [ ] design request
- [ ] other

### Current behavior

We can see on some figures where we need to click but it's unintuitive.
eg, https://brainhack.org/brainhack_cloud/admins/admins/#create-a-new-admin

### Expected behavior

Additional instruction mentioning the link and the steps.

### If the current behavior is a bug, please tell us about your environment

- [ ] all
- [ ] Chrome XX
- [ ] Firefox XX
- [ ] Internet explorer XX
- [ ] Safari XX
- [ ] Mobile Chrome XX
- [ ] Android X.X Web Browser
- [ ] iOS XX Safari
- [ ] iOS XX UIWebView
- [ ] iOS XX WKWebView

**Comment by stebo85** [comment]
should just be: https://cloud.oracle.com/?region=eu-frankfurt-1&tenant=brainhack

**Comment by SamGuay** [comment]
Sorry, I meant Procedure and not the link per se for the SSO vs username/password. I just want to make sure it's easy to spot from the get-go during the onboarding of a new admin/user.

I'll make the PR so you can see what I mean :smile:

**Comment by stebo85** [comment]
awesome :)

**Comment by stebo85** [comment]
@SamGuay - did you have a chance to work on this?

**Comment by SamGuay** [comment]
I guess we are all used by now :sweat_smile:
