### ISSUE TITLE
MLOpsZoomCamp ressource request

### ISSUE THREAD

**Issue by likeajumprope** [brainhackorg/brainhack_cloud#36]
### Title

Ressource request MLOPsZoomCamp

### Is this a new project?

yes

### People involved

@likeajumprope 

### Project Description

Both for the purpose of checking out the platform and because I am participating in the MlOpsZoomCamp, (https://github.com/DataTalksClub/mlops-zoomcamp) I'd like to request some ressources (see below). Also trying to figure out whether this might be a good way to teach people the usage of the cloud

### Link to project repository/sources

https://github.com/likeajumprope/mlops-zoomcamp

### What resources do you require?

Virtual Machines, Object Storage

### Anything else?

I guess I COULD just create this project myself as admin, but thought I'd better go the traditional way..

**Comment by stebo85** [comment]
Yes, but still important to have a record :) create the project and let me know if you need any help.

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
