### ISSUE TITLE
Oracle cloud on Readme.md github page

### ISSUE THREAD

**Issue by likeajumprope** [brainhackorg/brainhack_cloud#37]
The Oracle logo on the github Readme.md is made for dark mode and almost not visible in light mode. 
Potential solutions:
1. Logo that is visible in both dark and light mode
2. Conditional logo (as that possible?)

**Comment by Remi-Gau** [comment]
FYI

This is how we dealt with it on the github repo of the BIDS spec

```
<img src="./BIDS_logo/BIDS_logo_white_transparent_background_crop.png#gh-dark-mode-only" alt="bids-logo" width="600"/>
<img src="./BIDS_logo/BIDS_logo_black_transparent_background_crop.png#gh-light-mode-only" alt="bids-logo" width="600"/>
```

https://github.com/bids-standard/bids-specification/blob/3537e9edbc81545614d3ee605c398361099b6977/README.md?plain=1#L6

**Comment by complexbrains** [comment]
Thank you @Remi-Gau  it is a nice solution 🤗 

The funny thing is I cannot find where I found that logo from. Even on their [twitter](https://mobile.twitter.com/oracleresearch), they use this logo 
![image](https://user-images.githubusercontent.com/45263281/171300936-39657816-5ef7-4603-8d13-788c55d5fc3e.png)

I guess using this _official logo_ will resolve our problems in both 💡  modes 🙄
