### ISSUE TITLE
watts_up_compute

### ISSUE THREAD

**Issue by nikhil153** [brainhackorg/brainhack_cloud#43]
### Title

watts_up_compute

### Is this a new project?

no

### People involved

Nikhil Bhagwat, nikhil153, nikhil.bhagwat@mcgill.ca
Johanna Bayer, likeajumprope, https://www.linkedin.com/in/johanna-bayer
Sebastian Urchs, surchs, sebastian.urchs@mcgill.ca

### Integration of compute-tracker tools into neuroimaging pipelines to estimate carbon footprint of image processing

This is an ongoing project by the Sustainability and Environmental Action group ([SEA-SIG](https://ohbm-environment.org/)) at the Organisation for Human Brain Mapping (OHBM). In this project we aim at better understanding the environmental costs of commonly used research pipelines and develop tools to help reduce them.

Recently there have been several projects that track cpu/gpu "power draws" incurred during a compute task. These statistics can then be translated into carbon-footprint based on your location and time of processing.

### Link to project repository/sources

https://github.com/nikhil153/fmriprep/blob/carbon-trackers/singularity/carbon_trackers_readme.md

### What resources do you require?

HPC

**Comment by likeajumprope** [comment]
The login links and passwords have been sent out! Tag me if you need any more help :)

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
