### ISSUE TITLE
Big Linear Mixed Models

### ISSUE THREAD

**Issue by TomMaullin** [brainhackorg/brainhack_cloud#44]
### Title

Big Linear Mixed Models

### Is this a new project?

This is the first time we have posted it here. But it is a few years old.

### People involved

Thomas Maullin-Sapey @TomMaullin thomas.maullin-sapey@bdi.ox.ac.uk
Thomas Nichols @NicholsT thomas.nichols@bdi.ox.ac.uk
Vicente Ferrer @vinferrer v.ferrer@bcbl.eu

### Project Description

Large-scale, shared datasets are becoming increasingly commonplace in fMRI, challenging existing tools both in terms of overall scale and complexity of the study designs. As sample sizes grow, new opportunities arise to detect and account for grouping factors and covariance structures present in large experimental designs. To facilitate large sample analysis, we have created two Python toolboxes for use on HPC clusters:

 - “Big” Linear Models (BLM); a toolbox for large-scale distributed fMRI Linear Model analyses.
 - “Big” Linear Mixed Models (BLMM); a toolbox for large-scale distributed fMRI Linear Mixed Model analyses.

At present, both tools are functioning and can be used for the analysis of tens of thousands of fMRI images. However, there is plenty that could be improved. Some current goals include:

 1. Developing a rigorous testing suite, potentially with continuous integration via Travis CI.
 1. Using Dask to streamline the current code base (at present there are a lot of bash scripts for 'qsub'bing).
 1. Package releases. Neither of the toolboxes are currently on the Python Package Index.
 1. Adding customized covariance support. In previous work, we showed how the underlying methods BLMM uses could model custom covariance structures (e.g. AR, Diagonal, Toeplitz etc). However, at present BLMM does not support analyses with these features. 

### Link to project repository/sources

https://github.com/TomMaullin/BLMM

### What resources do you require?

HPC

### Anything else?

I believe we shouldn't need a virtual machine but as I am still learning how to use github actions (which we plan to use for continuous integration testing), this may change in future.

**Comment by likeajumprope** [comment]
Hi @TomMaullin I am creating access to the cloud for you now!

**Comment by likeajumprope** [comment]
Accounts were created, passwords were sent out

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
