### ISSUE TITLE
Deep learning for fMRI

### ISSUE THREAD

**Issue by Jinglei-Lv** [brainhackorg/brainhack_cloud#45]
### Title

Deep learning for fMRI

### Is this a new project?

yes

### People involved

jinglei.lv@sydney.edu.au

### Project Description

- What are you doing, for whom, and why?

### Link to project repository/sources

https://github.com/user_name/my_awesome_project

### What resources do you require?

GPU resources

**Comment by stebo85** [comment]
I am on it :)

**Comment by stebo85** [comment]
ok, done - all created :)

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
