### ISSUE TITLE
BrainHack Project 

### ISSUE THREAD

**Issue by Arshitha** [brainhackorg/brainhack_cloud#46]
### Title

I'm working on the NARPS project at BrainHack. I'm on a M1 macbook and having a hard time downloading data and installing required packages so I'd very much appreciate access to the cloud.

### People involved

arsh2794@gmail.com
@Arshitha

### Project Description

- What are you doing, for whom, and why?

### Link to project repository/sources

https://github.com/Inria-Empenn/narps_open_pipelines

### What resources do you require?

Virtual Machines, Object Storage, HPC

**Comment by stebo85** [comment]
working on this request

**Comment by Arshitha** [comment]
Thank you!!

**Comment by stebo85** [comment]
All created and ready to go @Arshitha - check your email inbox for login details and instructions.

**Comment by Arshitha** [comment]
Thanks @stebo85 ! I have access to the cloud now. Really appreciate your help!

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
