### ISSUE TITLE
HCPtrt_decoding

### ISSUE THREAD

**Issue by srastegarnia** [brainhackorg/brainhack_cloud#47]
### Title

Finding a way to plot weight maps from the outputs of non-linear decoder

### Is this a new project?

yes

### People involved

Shima Rastegarni

### Project Description

- What are you doing, for whom, and why?

### Link to project repository/sources

https://github.com/user_name/my_awesome_project

### What resources do you require?

GPU resources

**Comment by stebo85** [comment]
Dear @srastegarnia ,

We need an email address to setup the account.

All the best
Steffen

**Comment by stebo85** [comment]
You can post the email address here or in our discord/mattermost channels

**Comment by stebo85** [comment]
what gpus do you need? p100 or v100? in a vm or in datascience notebook?

**Comment by stebo85** [comment]
Dear @srastegarnia - do you still require these resources? If yes, we need more details as specified above: Your email adress, which GPU model you require and if you need the GPU in a VM or jupyter notebook.

Thank you
Steffen

**Comment by stebo85** [comment]
closing because there is not enough information to create the project and the project creator doesn't respond.
