### ISSUE TITLE
Access for development of ML models

### ISSUE THREAD

**Issue by sina-mansour** [brainhackorg/brainhack_cloud#48]
### Title

Participation in the [ATLAS R2.0 - Anatomical Tracings of Lesions After Stroke](https://atlas.grand-challenge.org/) Grand Challenge

### People involved

[Sina Mansour L.](https://sina-mansour.github.io/)
Niousha Dehestani

### Project Description

We will be developing various machine learning models for stroke lesion segmentation which we started working on during the OHBM brainhack in [this brainhack project](https://github.com/ohbm/hackathon2022/issues/75).

We'd require remote Linux servers (preferably with GPUs) to train various ML models for the challenge.

### Link to project repository/sources

We have not yet created a git repo, but will create one before completing the challenge and make it publicly available after the challenge [here](https://github.com/sina-mansour).

### What resources do you require?

Virtual Machines, Object Storage, GPU resources

### Anything else?

We would like to host a remote Linux server with ssh access. Here's a ballpark estimate of the required system specs:

- 16 CPU cores
- 128 GB memory
- 1TB storage
- GPU access for efficient training of deep learning models

We'll be able to configure the server to host a jupyter lab environment.

**Comment by stebo85** [comment]
We need email addresses to create the account. Can you send these to us (either here or mattermost/discord)

**Comment by stebo85** [comment]
The VM size is no problem and I reserved a v100 GPU in Tokyo for you.

**Comment by stebo85** [comment]
All created and good to go :)

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
