### ISSUE TITLE
Request ressources on brainhack_cloud for Github Actions runner for macapype package validation

### ISSUE THREAD

**Issue by davidmeunier79** [brainhackorg/brainhack_cloud#51]
### Title

 Github Actions runner for macapype package validation

### Is this a new project?

yes

### People involved

@davidmeunier79 @BastienCagna @oliviercoulon @kepkee

### Project Description

Macapype is a python package for segmentation of non-human primate anatomical MRI images; It runs on github, with unittests and PEP8 check on PR; For pre-relsease / release, we would like to validate full pipeline runs with some example data. However, the github server are limited in memory size availble for Github Actions, and for some stedp of the validation (namely using FSL fnirt) requires up to 30 Gb of RAM. Hence my request to  add brainhack_cloud ressources to run on release validation with github actions.

### Link to project repository/sources

https://github.com/Macatools/macapype
https://macatools.github.io/macapype/

### What resources do you require?

Virtual Machines

**Comment by stebo85** [comment]
All done and setup @davidmeunier79 - you should have an email with the account details :)

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
