### ISSUE TITLE
Access to brainhack cloud and sharing situation

### ISSUE THREAD

**Issue by kevinjamey** [brainhackorg/brainhack_cloud#52]
Hi,

I'm actually wondering at this point if I am allowed to use the brainhack cloud or not for the data I plan to use.

The participant consent for the data I want to use goes as follows:

"Individual identifying information will be kept confidential and only authorized personnel will have access to it. However, the Research Ethics Board or Quality Assurance Officers duly authorized by it may access study data.  Data will be coded (identifying information replaced by a code) and the code key will be kept in a separate secure location. The data from the study will be maintained in a secure database, and used for purposes of analysis and comparison with other data, and for scientific dissemination and publication in the Principal Investigator’s lab and collaborating labs."

What are your thoughts would there be any confidentiality breach in using the brainhack cloud?

Project plan:

For my dataset, I'm want to use data I collected at the MNI during my Master's (~5 GB in size). I have received the raw data on my computer already and there are about 50 children with autism who followed a music intervention with pre-post scans for 10 minutes of rsFMRI and a T1. There has already been a publication on it for auditory-motor networks: https://www.nature.com/articles/s41398-018-0287-3
So I would like to see if I can associate changes in resting-state functional connectivity with networks related to joint attention using the brain imaging data set. My plan would be to convert it to NIFTY and BIDS and then get it preprocessed by Beluga. I don't know exactly how many resources are necessary but I'm guessing 1 node is enough.

Thanks for any help!

**Comment by stebo85** [comment]
Dear @kevinjamey 

It's difficult to give advice on this. The cloud is very flexible and you can do whatever you like - this also means you can make it as secure as you like or as unsecure as you like. 

"The data from the study will be maintained in a secure database" - if you know how run such a secure database on the cloud then I think it would be fine. If you don't know, then it's not ok.

I hope that helps
Kind regards
Steffen

**Comment by SamGuay** [comment]
> then get it preprocessed by Beluga

Just to add a little bit on the matter @kevinjamey, if you plan to use [Beluga or Narwhal](https://docs.alliancecan.ca/wiki/Narval/en) (clusters in Quebec for those reading outside of Canada), I would advise **NOT using** the Brainhack Cloud for some steps then move all the data considering your Ethics doubts As your data were collected at the MNI, I think it would be more coherent to use resources already available for you like you intended to use anyway. 

> My plan would be to convert it to NIFTY and BIDS

You can easily do this step locally on your machine as you already have the data on your local machine. You can use something like [dcm2bids](https://unfmontreal.github.io/Dcm2Bids/) (lightweight) or [bidscoin](https://bidscoin.readthedocs.io/en/stable/) (heavier) for example to convert you data into a bids dataset, then upload these data to a cluster and preprocess the data with fMRIprep for example.

**Comment by kevinjamey** [comment]
Thanks, @SamGuay  ! This sounds like a good plan.
