### ISSUE TITLE
Request resource access for Benchmark denoising strategies on fMRIPrep output

### ISSUE THREAD

**Issue by htwangtw** [brainhackorg/brainhack_cloud#54]
### Title

Benchmark denoising strategies on fMRIPrep output

### Is this a new project?

yes

### People involved and contact details (including email address!)

Hao-Ting Wang @htwangtw htwangtw@gmail.com

### Project Description

The project is a continuation of [load_confounds](https://github.com/SIMEXP/load_confounds). The aim is to evaluate the impact of denoising strategy on functional connectivity data, using output processed by fMRIPrep LTS.

The main tool is now a part of [nilearn](https://nilearn.github.io/stable/modules/generated/nilearn.interfaces.fmriprep.load_confounds.html#nilearn.interfaces.fmriprep.load_confounds).

### Link to project repository/sources

https://github.com/SIMEXP/fmriprep-denoise-benchmark

### What resources do you require?

HPC

**Comment by stebo85** [comment]
All created and ready to go for you @htwangtw

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
