### ISSUE TITLE
Request for access to BH cloud services

### ISSUE THREAD

**Issue by PeteBro** [brainhackorg/brainhack_cloud#55]
### Title

Identifying Neuropsychiatric Diagnoses using fMRI Connectivity Data.

### Is this a new project?

yes

### People involved and contact details (including email address!)

Peter Brotherwood (peter.brotherwood@umontreal.ca)

### Project Description

- What are you doing, for whom, and why?
Requesting access to HPC services for utilisation during my brainhack school project.

### Link to project repository/sources

https://github.com/brainhack-school2022/brotherwood_project

### What resources do you require?

HPC

**Comment by stebo85** [comment]
@likeajumprope @complexbrains @SamGuay - can please someone of you create the account?

**Comment by likeajumprope** [comment]
Done - @PeteBro you should have received two emails giving you access to the cloud. Let us know if you have any questions.

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
