### ISSUE TITLE
Resource Request for BrainHack School Purposes

### ISSUE THREAD

**Issue by Andjelaaaa** [brainhackorg/brainhack_cloud#56]
### Title

BrainHack School project to do some freesurfer analysis on 3D MRI structural images

### Is this a new project?

yes

### People involved and contact details (including email address!)

andjeladimi98@gmail.com (@Andjelaaaa)

### Project Description

- What are you doing, for whom, and why?
This project consists of running an automated script for freesurfer analysis on 3D brain data for the BrainHack School happening this summer 2022.

### Link to project repository/sources

https://github.com/Andjelaaaa/dimitrijevic_project

### What resources do you require?

Virtual Machines, Object Storage, GPU resources, HPC

### Anything else?

If this could be approved quickly that would be great! Thanks in advance,

Andjela Dimitrijevic

**Comment by likeajumprope** [comment]
done

**Comment by stebo85** [comment]
Dear @Andjelaaaa 

It sounds like our project www.Neurodesk.org could be useful for your application? It contains freesurfer and all tools required for such an analysis.

you can test it out here: https://play.neurodesk.org/v2/gh/neurodesk/jupyter-neurodesktop-image/main?urlpath=neurodesktop

If you like to run your own Neurodesk server, I described this as part of the docker setup:
https://brainhack.org/brainhack_cloud/docs/docker/

and the setup is described in detail here:
https://www.neurodesk.org/docs/neurodesktop/getting-started/cloud/

**Comment by Andjelaaaa** [comment]
Hi,

Thank you so much! I’ll have a look tomorrow. If I have any questions, I’ll follow up with you.

Thanks again,

Andjela Dimitrijevic

**Comment by Andjelaaaa** [comment]
> 

Hi, 

I tried testing out the neurodesk which you sent me and there's a license issue. Do I need to add another license file as indicated ? Here is the shown error message below 
`ERROR: FreeSurfer license file /usr/local/freesurfer/.license not found.
  If you are outside the NMR-Martinos Center,
  go to http://surfer.nmr.mgh.harvard.edu/registration.html to 
  get a valid license file (it's free).
  If you are inside the NMR-Martinos Center,
  make sure to source the standard environment.
  A path to an alternative license file can also be
  specified with the FS_LICENSE environmental variable. `
![image](https://user-images.githubusercontent.com/46799444/181370512-156a84db-1682-4b60-8c5a-2b72093cc42e.png)

**Comment by stebo85** [comment]
Dear @Andjelaaaa,

Correct - as described in my response to your other issue: 

You need to request a license file and set it up.

This is described in our FAQ as well: https://www.neurodesk.org/docs/faq/#freeview-720-crashes-when-i-open-files


When you run:
```
echo "Steffen.Bollmann@cai.uq.edu.au
> 21029
>  *Cqyn12sqTCxo
>  FSxgcvGkNR59Y" >> ~/.license

export FS_LICENSE=~/.license 
```

then 
```
ml freesurfer/7.2.0
```

everything should work perfectly.

Can you test this and let know if this works?


Kind regards
Steffen

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
