### ISSUE TITLE
Brainhack school 22 resource request - Twin normative modelling

### ISSUE THREAD

**Issue by likeajumprope** [brainhackorg/brainhack_cloud#57]
### Title

Twin normative modelling

### Is this a new project?

yes

### People involved and contact details (including email address!)

@likeajumprope

### Project Description

I'd need a notebook resource for the brainhack school 22 to do normative modelling on a twin data set

### Link to project repository/sources

https://github.com/likeajumprope/normative_twins_project

### What resources do you require?

Virtual Machines, HPC

**Comment by stebo85** [comment]
@likeajumprope - do you still need this? Should I create the resource for you?

**Comment by likeajumprope** [comment]
Ah no, I created my own resource and forgot to close this issue!

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
