### ISSUE TITLE
 NeuroDesk Installation tutorial for the cloud

### ISSUE THREAD

**Issue by likeajumprope** [brainhackorg/brainhack_cloud#58]
It might be nice to have a tutorial for folks on how to run NeuroDesk on the cloud

**Comment by stebo85** [comment]
Dear @likeajumprope,

I described this as part of the docker setup:
https://brainhack.org/brainhack_cloud/docs/docker/

and it's described in detail here:
https://www.neurodesk.org/docs/neurodesktop/getting-started/cloud/

**Comment by stebo85** [comment]
I am adding a separate section now so that it's more obvious

**Comment by stebo85** [comment]
ok, done - can you check @likeajumprope?

**Comment by likeajumprope** [comment]
Looks great! Thanks @stebo85
