### ISSUE TITLE
Request for resources for @vsoch

### ISSUE THREAD

**Issue by vsoch** [brainhackorg/brainhack_cloud#61]
### Title

tunel: apps for high performance computing

### Is this a new project?

no

### People involved and contact details (including email address!)

@vsoch (email provided to sbollmann_MRI on Twitter

### Project Description

- What are you doing, for whom, and why?
Tunel is a "bring your own apps" framework for HPC. It makes it easy to launch (typically locally developed and constrained) applications via unix sockets, either to a cluster node or jobs nodes via this method. I am seeking minimal access to resources (likely an infrequent access to a login node + single job node) to continue the development of the slurm launcher. I no longer have access to a SLURM cluster and have been testing with the open science grid (htcondor without node access).

### Link to project repository/sources

 - Main GitHub Organization: https://github.com/tunel-apps
 - Tunel Software: https://github.com/tunel-apps/tunel
 - Documentation: https://tunel-apps.github.io/tunel/
 - Apps: https://tunel-apps.github.io/tunel/_static/apps/

### What resources do you require?

HPC

### Anything else?

I only require access to a login node and a worker node, not even anything substantially impressive in terms of memory or compute!

**Comment by stebo85** [comment]
done :)

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.

**Comment by vsoch** [comment]
Thanks for the help on this last year, it was fun to try out!
