### ISSUE TITLE
Request resources for NeuroCausal project

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/brainhack_cloud#65]
### Title

NeuroCausal: an open source platform for the storage, sharing, synthesis and meta-analysis of neuropsychological data.

### People involved and contact details (including email address!)

Project leads
@vborghe Valentina Borghesani 
@Sladja13 Sladjana Lukic
@pinheirochagas Pedro PINHEIRO-CHAGAS
@complexbrains Isil Bilgin 

will send the emails separately.

### Project Description

We are working with clinicians, neuroimagers, and software developers to develop an open source platform for the storage, sharing, synthesis and meta-analysis of human clinical data to the service of the clinical and cognitive neuroscience community so that the future of neuropsychology can be transdiagnostic, open, and FAIR.

### Link to project repository/sources

https://github.com/neurocausal

### What resources do you require?

HPC

### Anything else?

We require access to a login & worker node and ~500 GB memory with internet access that will allow us to download/scrap papers using PubMed API and process/analyze the metadata

**Comment by stebo85** [comment]
@complexbrains - are you creating the account yourself? Let me know if you need a hand ✋

Cheers
Steffen

**Comment by complexbrains** [comment]
Thank you so much Steffen. I should be able to, just dropped a dm for Johanna to renew my account 🙈 then hopefully I should be able to do it. The only question I might request your help with maybe whether would we have internet access to download papers do you think or any restrictions regarding using PubMed API that you might think of? Then I will work on with the rest. Thank you so much 🤗

**Comment by stebo85** [comment]
There are no restrictions I am aware of and that should work. You ticked in the issue that you need HPC, but I would recommend to start with a VM.

let me know if you need anything else
Steffen

**Comment by stebo85** [comment]
closing as this seems to be done? Please reopen if it's not the case

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
