### ISSUE TITLE
Transcript alignment

### ISSUE THREAD

**Issue by complexbrains** [brainhackorg/brainhack_cloud#74]
### Title

The project requires usage of a docker container to extract time stamps of subtitles of a show to be aligned with the fMRI data. 

### Is this a new project?

yes

### People involved and contact details (including email address!)

Isil Bilgin 

### Project Description

- What are you doing, for whom, and why

### Link to project repository/sources

https://github.com/user_name/my_awesome_project

### What resources do you require?

Virtual Machines

**Comment by complexbrains** [comment]
Done

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
