### ISSUE TITLE
Resource request for bayes-on-the-brain

### ISSUE THREAD

**Issue by garner-code** [brainhackorg/brainhack_cloud#76]
### Title

Bayes on the brain in python

### People involved and contact details (including email address!)

Preethom Pal @pregon pal.pree@gmail.com
Megan Campbell @meganEJcampbell megan.ej.campbell@gmail.com
Isabella Orlando @isabellaorlando iorl8844@uni.sydney.edu.au
Darin @dsleiter darin@ae.studio
Adam @a-manoogian adammanoogian@gmail.com
Kelly Garner @kel-github getkellygarner@gmail.com

### Project Description

- Running Bayesian mixture models on fmri data to test its viability as a computational approach

### Link to project repository/sources

https://github.com/crnolan/pyrba

### What resources do you require?

Virtual Machines, Object Storage, GPU resources, HPC

**Comment by stebo85** [comment]
all done.

**Comment by stebo85** [comment]
project ended. shutting down all resources now

**Comment by QA-Pregon** [comment]
Weird question, but why was I listed as Preethom Pal, I have no idea what you guys were doing here. I think it was a mistake.

**Comment by stebo85** [comment]
Dear @Pregon - not sure :) But someone tagged your github username there. Don't worry - such things can happen.

**Comment by Pregon** [comment]
Allright, I already forgot about this was happening but now there was a massage.
Am I allowed to ask what you have worked on the past year?

**Comment by stebo85** [comment]
This project was for cloud credits on the Oracle Cloud to process human imaging data.
