### ISSUE TITLE
Layout of landing page: suboptimal responsiveness

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/brainhack_cloud#8]
For certain devices the layout will not be optimal.

![Screenshot from 2022-03-09 08-01-02](https://user-images.githubusercontent.com/6961185/157389840-c294a3e6-3d57-475c-98c0-d864622fd422.png)

**Comment by stebo85** [comment]
no one seems to be working on this. Closing. Please feel free to reopen.
