### ISSUE TITLE
Request resource access for BrainHackHFX-2023

### ISSUE THREAD

**Issue by hfxcarl** [brainhackorg/brainhack_cloud#82]
### Title

Hi, I'm co-hosting BrainHackHFX 2023 in Halifax, Nova Scotia and hoping to try out the BrainHack Cloud Computing resources.  https://neural-data-science-hackathon.github.io/BrainHackHFX_global2023/

### Is this a new project?

yes

### People involved and contact details (including email address!)

Carl Helmick, affilliation="Dalhousie University, Psychiatry Dept", GitHubID="hfxcarl", email="chelmick@dal.ca".

### Project Description

I am co-hosting a smallish (30-50 people) brain hackathon in Halifax, NS. I'm looking for some cloud computing resources that will allow running simultaneous hacker code on relatively small datasets for the 3-day event.

### Link to project repository/sources

https://neural-data-science-hackathon.github.io/BrainHackHFX_global2023/

### What resources do you require?

Virtual Machines, Object Storage, GPU resources, HPC

### Anything else?

Assuming there would be options for running Jupyter notebooks in either the HPC or VM?

**Comment by stebo85** [comment]
Dear @hfxcarl,

All setup and ready to go :)

Please note that this project will end in December 2023 and all resources in this cloud account will be deleted in January 2024.

Yes, you can run Jupyter notebooks yourself on VMs (http://brainhack.org/brainhack_cloud/tutorials/vm/) or the HPC stack (http://brainhack.org/brainhack_cloud/tutorials/hpc/) or you can deploy Neurodesk (http://brainhack.org/brainhack_cloud/tutorials/neurodesk/) or you can use the Oracle Cloud notebook stack (http://brainhack.org/brainhack_cloud/tutorials/notebooks/)

Thank you 
Steffen

**Comment by stebo85** [comment]
This project is now closed and all resources on the Oracle Cloud will be deleted within the next few days.
